version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "com.android.application"
        update-types: ["version-update:semver-major"]
      - dependency-name: "gradle"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.jetbrains.kotlin.android"
        update-types: ["version-update:semver-major"]
